import numpy as np
arr=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
# print(arr)
print(len(arr))
print(arr.shape)
print(arr.size)
print(type(arr))
print(arr.dtype)
print(arr.astype(str))
print(np.ndim(arr))
